// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMtyRaaZLQG8ze87mbZ3a7a5Q3nGscGQ',
    appId: '1:586899360059:web:6d08614600d16c42ea4f1e',
    messagingSenderId: '586899360059',
    projectId: 'nutreasy-b8ec0',
    authDomain: 'nutreasy-b8ec0.firebaseapp.com',
    storageBucket: 'nutreasy-b8ec0.appspot.com',
    measurementId: 'G-2PKDVELQ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhpzGAq6w5o2Z0xFEk6aFpzp0WcWkH8M',
    appId: '1:586899360059:android:dd4861437bf5f7bfea4f1e',
    messagingSenderId: '586899360059',
    projectId: 'nutreasy-b8ec0',
    storageBucket: 'nutreasy-b8ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbniIbnJGQPshXLlYCJa-zlJJI2YkiawI',
    appId: '1:586899360059:ios:98129d8627efb689ea4f1e',
    messagingSenderId: '586899360059',
    projectId: 'nutreasy-b8ec0',
    storageBucket: 'nutreasy-b8ec0.appspot.com',
    iosClientId: '586899360059-m195701cth9sppii5q0afkia3shj8o3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbniIbnJGQPshXLlYCJa-zlJJI2YkiawI',
    appId: '1:586899360059:ios:eab0c24b81b952d7ea4f1e',
    messagingSenderId: '586899360059',
    projectId: 'nutreasy-b8ec0',
    storageBucket: 'nutreasy-b8ec0.appspot.com',
    iosClientId: '586899360059-bi5doanakeflt0iibg0umcke4q6regm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthBloc',
  );
}
